import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { clpl } from "@/config/clpl";
import GlobalStateWrapper from "./component/GlobalStateWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Geeleed Hotel",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/image/icon/logo_svg.svg" />
        <meta name="theme-color" content="#28221e" />
      </head>
      <body
        className={inter.className + " font-[IBMPlexSansThai]"}
        style={{ backgroundColor: clpl.c1 }}
      >
        <GlobalStateWrapper>{children}</GlobalStateWrapper>
      </body>
    </html>
  );
}
